routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MotorbikeController@index')->name('motorbike.list');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('motorbike','MotorbikeController',[
    'only'=>['store','show']
]);
Route::resource('event','Event\EventController');

app/Motorbike.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Motorbike extends Model
{
    protected $guarded=[];
    protected $table='motorbikes';
    protected $fillable=[
      'model',
      'color',
      'weight',
      'price',
      'image'
    ];
}

app/User.php
<?php

namespace App;

use App\Modules\Event\Event;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function events()
    {
        return $this->hasMany(Event::class,'user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Event/EventController.php
<?php

namespace App\Http\Controllers\Event;

use App\Modules\Event\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EventController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['create', 'show']]);
    }

    public function index()
    {
        $tody = Carbon::today()->format('Y-m-d');
        $upcomingEvents = Event::where('end_date', '>', $tody)->orderBy('start_date', 'desc')->get();
        $pastEvents = Event::where('end_date', '<', $tody)->orderBy('start_date', 'desc')->limit(3)->get();

        return view('events.index', compact('upcomingEvents', 'pastEvents'));
    }

    public function show(Event $event)
    {
        return view('events.show')->with('event', $event);
    }

    public function create()
    {
        return 'crate view';
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MotorbikeController.php
<?php

namespace App\Http\Controllers;

use App\Motorbike;
use foo\bar;
use Illuminate\Http\Request;

class MotorbikeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //

        $url=$request->fullUrl();
        $param=$request->input('sortByColor');
        $motobikes = Motorbike::orderBy('created_at', 'DESC')->paginate(5);
        return view('motorbikes.index', ['motorbikes'=>$motobikes, 'url'=>$url, 'param'=>$param]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                'model'=>'required|string|max:255',
                'color'=>'required|',
                'weight'=>'required|integer|max:250',
                'price'=>'required|integer|max:250',
                'image'=>'required|image|mimes:jpg,jpeg,png,gif|max:2048',
        ]);
        $name=$request->file('image')->getClientOriginalName();
        $request->file('image')->storeAs('motorbikes', $name);
        $motorbike = new Motorbike([
            'model'=>$request->input('model') ,
            'color'=>$request->input('color') ,
            'weight'=>$request->input('weight') ,
            'price'=>$request->input('price') ,
            'image'=>$name
        ]);
        $motorbike->save();

        session()->flash('message', 'Motorbike has been created');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Motorbike  $motorbike
     * @return \Illuminate\Http\Response
     */
    public function show(Motorbike $motorbike)
    {
        //

        return view('motorbikes.show', compact('motorbike'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Motorbike  $motorbike
     * @return \Illuminate\Http\Response
     */
    public function edit(Motorbike $motorbike)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Motorbike  $motorbike
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Motorbike $motorbike)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Motorbike  $motorbike
     * @return \Illuminate\Http\Response
     */
    public function destroy(Motorbike $motorbike)
    {
        //
    }
}

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if(count($upcomingEvents) ===0)
                    <div class="alert alert-warning text-capitalize text-center">
                        Empty Upcommig Events
                    </div>
                    @else
                    <div class="card ">
                        <div class="card-header">{{ __(' Upcoming Event Lists') }}</div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Address</th>
                                    <th>Start Date</th>
                                    <th>By</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($upcomingEvents as $event)
                                    <tr>
                                        <td>{{  $loop->index+1}} </td>
                                        <td><a href="{{route('event.show',$event)}}">{{ $event->title }}</a></td>
                                        <td>
                                            {{$event->address}}
                                        </td>
                                        <td>{{ $event->start_date }}</td>
                                        <td>{{ $event->user->name }}</td>

                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                    @endif
                <br>

            </div>
            <div class="col-md-8">
                @if(count($pastEvents) ===0)
                    <div class="alert alert-warning text-capitalize text-center">
                        Empty Upcommig Events
                    </div>
                @else
                <div class="card bg-secondary">
                    <div class="card-header">{{ __(' Past Event Lists') }}</div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Address</th>
                                <th>Start Date</th>
                                <th>By</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($pastEvents as $event)
                                <tr>
                                    <td>{{  $loop->index+1}} </td>
                                    <td><a href=" ">{{ $event->title }}</a></td>
                                    <td>
                                            {{  $event->address }}
                                      </td>
                                    <td>{{ $event->start_date }}</td>
                                    <td>{{ $event->user->name }}</td>

                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
                @endif
                <br>

            </div>
        </div>
    </div>
    @stop

resources/views/events/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">


            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Show ') }} {{ $event->name }}</div>
                    <div class="card-body">
                        <p class="text-left">
                            Description:
                        </p>
                        <p>
                            {!! $event->description !!}
                        </p>
                    </div>
                    <div id="map"></div>
                    <table class="table table-bordered mt-3">

                        <tbody>
                        <tr>
                            <th class="table-active">Start date</th>
                            <td>{{ $event->start_date }}</td>
                        </tr>
                        <tr>
                            <th class="table-active">End date</th>
                            <td>{{ $event->end_date }}</td>
                        </tr>
                        <tr>
                            <th class="table-active">Address</th>
                            <td>{{ $event->address }}</td>
                        </tr>
                        <tr>
                            <th class="table-active">By</th>
                            <td>{{ $event->user->name }}</td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                <br>
            </div>

        </div>
    </div>
@endsection

@section('header-style')
    <style>
        #map {
            width: 100%;
            border: 1px dashed #333;
            height: 300px;
        }
    </style>
@endsection
@section('footer-script')
    <script>
        //// show maps
        function getMaps() {
            var canvas = $('#map');
            var mapOptions = {
                center: new google.maps.LatLng({{$event->lat}}, {{$event->long}}),
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(canvas[0], mapOptions);
        }

        // getMaps();
    </script>
    <script async
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCdkY5JMQymRr-LDW4kpAfO8IKEUmD_ZnI&?callback=getMaps"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">


                        <div class="col-md-8">
                            @if(session()->has('message')))
                              <div class="alert text-center alert-success">
                                  {{ session('message') }}
                              </div>
                            @endif
                            <div class="card">
                                <div class="card-header">{{ __('Register Motorbike') }}</div>

                                <div class="card-body">
                                    <form method="POST" action="{{ route('motorbike.store') }}" aria-label="{{ __('Register Motorbike') }}" enctype="multipart/form-data">
                                        @csrf

                                        <div class="form-group row">
                                            <label for="model" class="col-md-4 col-form-label text-md-right">{{ __('Model') }}</label>

                                            <div class="col-md-6">
                                                <input id="model" type="text" class="form-control{{ $errors->has('model') ? ' is-invalid' : '' }}" name="model" value="{{ old('model') }}"  autofocus>

                                                @if ($errors->has('model'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('model') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="color" class="col-md-4 col-form-label text-md-right">{{ __('Color') }}</label>

                                            <div class="col-md-6">
                                                <select name="color" id="color" class="form-control">
                                                    <option disabled>Plaese Select a Color</option>
                                                    <option value="red">Red</option>
                                                    <option value="black">Black</option>
                                                    <option value="yellow">yellow</option>
                                                </select>
                                                @if ($errors->has('color'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('color') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="weight" class="col-md-4 col-form-label text-md-right">{{ __('Weight') }}</label>

                                            <div class="col-md-6">
                                                <input id="weight" type="number" class="form-control{{ $errors->has('weight') ? ' is-invalid' : '' }}" name="weight" required>

                                                @if ($errors->has('weight'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('weight') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                                            <div class="col-md-6">
                                                <input id="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price" required>

                                                @if ($errors->has('price'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="image" class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                                            <div class="col-md-6">
                                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image" required>

                                                @if ($errors->has('image'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row mb-0">
                                            <div class="col-md-6 offset-md-4">
                                                <button type="submit" class="btn btn-primary">
                                                    {{ __('Register Motorbike') }}
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    @yield('header-style')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('event.index')}}">Events</a>
{{--                            <a class="nav-link" href="{{route('motorbike.list')}}">Motorbikes</a>--}}
                        </li>
                        @guest
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="home">Add Motorbike</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('event.create')}}">Add Event</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
@yield('footer-script')
</body>
</html>

resources/views/motorbikes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">


            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __(' Motorbike Lists') }}</div>

                    <div class="card-body">

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Model</th>
                                    <th>Color</th>
                                    <th>Weight</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach($motorbikes as $motorbike)
                                <tr>
                                    <td>{{  $loop->index+1}} </td>
                                    <td><a href="{{ route('motorbike.show',$motorbike) }}">{{ $motorbike->model }}</a></td>
                                    <td>
                                        <p class="badge " style="color:{{ $motorbike->color }};width: 30px;height: 30px;display: block">
                                            <a href="{{ url('/') }}?sortByColor={{  $motorbike->color }}">

                                            {{ $motorbike->color }}
                                            </a>
                                        </p></td>
                                    <td>{{ $motorbike->weight }}</td>
                                    <td>{{ $motorbike->price }}</td>

                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
                <br>
                <div class="text-center"> {{ $motorbikes->appends(['sortByColor' => Request::input('sortByColor')])->links()}}</div>
            </div>

        </div>
    </div>
    @stop

resources/views/motorbikes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">


            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Show ') }} {{ $motorbike->model }}</div>

                    <div class="card-body">

                        <ul  class="list-group motorbike-group">
                            <li class="list-item">
                            {{ $motorbike->model }}
                            </li>
                            <li class="list-item">
                               <div class="" style="width: 40px;height: 40px; background: {{   $motorbike->color }}"></div>
                            </li>
                            <li class="list-item">
                                {{ $motorbike->weight }} Kg
                            </li>
                            <li class="list-item">
                                {{ $motorbike->price }} Rial
                            </li>
                           <li>
                               <figure class="figure">
                                   <img style="width: 300px;height: 250px;" src="/storage/motorbikes/{{ $motorbike->image}}" class="img-circle" alt=" {{ $motorbike->model }}">
                               </figure>
                           </li>
                        </ul>
                    </div>
                </div>
                <br>
            </div>

        </div>
    </div>
    @stop